name = "buddy-api"
main = "src/index.ts"
minify = true
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]
routes = [
  { pattern = "apibuddy.allix.xyz", custom_domain = true },
]